### ISSUE TITLE
your system whith 1.4 update is more difficult

### ISSUE THREAD

**Issue by tristan1111** [ppppuProgrammer/ppppuNX#19]
hello please corrige your files an version not locked by the mods, i's boring, , not mods please just likes the others versions , just clic and play select characters etc, because yours explications for the mods d'ont work and its boring to shearch a solution beacause they are no tutoriel vidéo

**Comment by ppppuProgrammer** [comment]
I'm having trouble understanding your comment but from what I see it doesn't even pertain to this project as NX hasn't even reach v1.0. Closing this issue.
